_fillInDataModel(
        'com.tenze.pms.facade.dto.his.HisFeeSettleDto',
        {
            table:Ext_UiTable({
                beanId:'hisFeeSettleId',
                beanName:'hisFeeSettleName',
                formLayout:'hbox',
                hboxColumnCount:2
            })
            ,
            fields:[
                    Ext_UiField({type:'string',name:'id',text:'id',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                    Ext_UiField({type:'string',name:'version',text:'version',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                    Ext_UiField({type:'string',name:'updatetime',text:'updatetime',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                    Ext_UiField({type:'string',name:'fdelFlag',text:'fdelFlag',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'createtime',text:'创建时间',xtype:'hidden',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'merName',text:'商家名称',xtype:'btnfield',hidden:false,allowBlank:true,queryFlag:true}),
                 //Ext_UiField({type:'string',name:'merInsName',text:'商户名称',xtype:'btnfield',hidden:false,allowBlank:true,queryFlag:true}),
                 //Ext_UiField({type:'string',name:'ykc675',text:'结算类型',xtype:'combobox',datadic:'ykc675',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'aae040',text:'结算时间',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'akc264',text:'医疗费总额',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'akc253',text:'本次就诊政策范围外个人自费金额',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                // Ext_UiField({type:'string',name:'akc254',text:'本次就诊政策范围内个人自付金额',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'yka319',text:'允许报销部分',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 Ext_UiField({type:'string',name:'ykc624',text:'个人支付金额',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'aka151',text:'本次就诊基本医疗保险统筹基金起付标准额',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'akb066',text:'个人账户支付金额合计',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'ykc631',text:'超报销限额自付金额',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'akb068',text:'统筹支付金额合计',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'ake039',text:'基本医疗保险统筹基金支付金额',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'ykc627',text:'基本医疗统筹自付部分',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'ckc504',text:'补充医疗统筹支付',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'ckc688',text:'补充医疗分段自付',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'akc630',text:'大病医疗统筹支付部分',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'ykc629',text:'大病医疗统筹自付部分',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 //Ext_UiField({type:'string',name:'akb063',text:'住院天数',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 Ext_UiField({type:'string',name:'ykc618',text:'结算业务号',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'ykc666',text:'自费原因',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'yka430',text:'统筹累计已支付',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'yka431',text:'补充医疗累计已支付',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'yka402',text:'共付段个人支付',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'ckc938',text:'民政补助金额',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'ckc939',text:'民政自付段金额',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'ckc940',text:'预留报销金额1',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'ckc941',text:'预留自付金额1',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'ckc942',text:'预留报销金额2',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'ckc943',text:'预留自付金额2',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'ckc944',text:'预留报销金额3',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'ckc945',text:'预留报销金额3',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'aae013',text:'备注',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'ckeA0N',text:'原计算信息标志',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:false}),
                 // Ext_UiField({type:'string',name:'merId',text:'merId',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 // Ext_UiField({type:'string',name:'merNoId',text:'merNoId',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
            ]
    }        
);