_fillInDataModel(
        'com.tenze.pms.facade.dto.his.HisSettleDtlDto',
        {
            table:Ext_UiTable({
                beanId:'hisSettleDtlId',
                beanName:'hisSettleDtlName',
                formLayout:'hbox',
                hboxColumnCount:2
            })
            ,
            fields:[
                    Ext_UiField({type:'string',name:'id',text:'id',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                    Ext_UiField({type:'string',name:'version',text:'version',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                    Ext_UiField({type:'string',name:'createtime',text:'createtime',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                    Ext_UiField({type:'string',name:'updatetime',text:'updatetime',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                    Ext_UiField({type:'string',name:'fdelFlag',text:'fdelFlag',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'ykc610',text:'医疗费用序列号',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'yka111',text:'大类名称',xtype:'textfield',datadic:'yka111',hidden:false,allowBlank:true,queryFlag:true}),                 
                 Ext_UiField({type:'string',name:'yka112',text:'大类名称',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'akc222y',text:'项目代码',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'akc223y',text:'项目名称',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'akc226',text:'数量',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'akc225',text:'单价',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'akc264',text:'小计',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'akc221',text:'处方单据时间',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'aae011',text:'aae011',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'masId',text:'masId',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
            ]
        ,Supcan:{
        	TreeList:{
        		Cols:[
        		      {'@name':'akc222y','#':'项目代码',DropList:{DropListId:'customer12',type:'EditAbleDropTreeList',DataCol:'settleNo',DisplayCol:'settleNo'}}
        		      ,{'@name':'akc223y','#':'项目名称','@editAble':false}
        		      ,{'@name':'ykc610','#':'医疗费用序列号','@editAble':false}
        		      ,{'@name':'yka111','#':'大类名称', DropList:{DropListId:'DropList_yka111',type:'DropList',datadic:'yka111'} ,'@editAble':false}
        		      ,{'@name':'yka112','#':'大类名称','@editAble':false,'@isHide':true}
        		      ,{'@name':'akc226','#':'数量','@decimal':2}
        		      ,{'@name':'akc225','#':'单价','@decimal':2,'@editAble':false}
        		      ,{'@name':'akc264','#':'小计','@decimal':2,'@editAble':false}
        		      ,{'@name':'akc221','#':'处方单据时间','@dataType':'date','@defaultValue':'=now()'}
        		      ,{'@name':'aae311','#':'医嘱结束时间','@dataType':'datetime','@defaultValue':'=now()'}
        		      ,{'@name':'aae011','#':'','@isHide':true}
        		      ,{'@name':'masId','#':'主表编号','@isHide':true}
        		      ,{'@name':'id','#':'id','@editAble':false,'@isHide':true}
        		      ,{'@name':'version','#':'version','@editAble':false,'@isHide':true,'@defaultValue':0}
        		      ,{'@name':'fdelFlag','#':'fdelFlag','@editAble':false,'@isHide':true,'@defaultValue':0}
        		]
        	}
        }
    }        
);