_fillInDataModel(
        'com.tenze.pms.facade.dto.his.HisSettleDto',
        {
            table:Ext_UiTable({
                beanId:'hisSettleId',
                beanName:'hisSettleName',
                formLayout:'hbox',
                hboxColumnCount:2
            })
            ,
            fields:[
                 Ext_UiField({type:'string',name:'id',text:'id',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'version',text:'version',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'createtime',text:'createtime',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'updatetime',text:'updatetime',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'fdelFlag',text:'fdelFlag',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'merId',text:'merId',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'merName',text:'所属商家',xtype:'btnfield',readOnly:true,hidden:false,allowBlank:false,queryFlag:true}),
                 Ext_UiField({type:'string',name:'hisNo',text:'医院编码',xtype:'textfield',readOnly:true,hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'settleType',text:'结算费用类型',xtype:'combobox',datadic:'yka111',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'settleNo',text:'项目代码',xtype:'textfield',hidden:false,allowBlank:false,queryFlag:true}),
                 Ext_UiField({type:'string',name:'cnName',text:'项目中文名',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'mnemonicCode',text:'助记码',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'enName',text:'项目英文名',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'commonName',text:'通用名',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'preparation',text:'规格',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'hisCatetoryId',text:'hisCatetoryId',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'hisCategoryName',text:'医院分类名称',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'price',text:'单价',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'unitId',text:'unitId',xtype:'hidden',hidden:true,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'unitName',text:'单位',xtype:'btnfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'internationalCode',text:'国际码',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'effectTime',text:'生效日期',xtype:'datefield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'remark',text:'备注',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
                 Ext_UiField({type:'string',name:'socialSecurityProjectCode',text:'社保项目编码',xtype:'textfield',hidden:false,allowBlank:true,queryFlag:true}),
            ]
        ,Supcan:{
        	TreeList:{
        		Properties:{
        			
        		},
        		Cols:[
        		      {'#':'所属商家','@name':'merName'}
        		      ,{'#':'项目代码','@name':'settleNo'}
        		      ,{'#':'项目名称','@name':'cnName'}
        		      ,{'#':'助记码','@name':'mnemonicCode'}
        		      ,{'#':'结算费用类型','@name':'settleType','@defaultValue':'B24',DropList:{DropListId:'DropList_ak130',type:'DropList',datadic:'ak130'}}
        		      ,{'#':'单价','@name':'price'}
        		]
        	}
        }
    }        
);